
# k8s-manifests/wordpress/wordpress-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_REDIS_HOST', 'redis-service');
            define('WP_REDIS_PORT', 6379);
            define('WP_REDIS_DATABASE', 0);
            define('WP_DEBUG', false);
            define('WP_DEBUG_LOG', true);
            define('WP_DEBUG_DISPLAY', false);
            define('FS_METHOD', 'direct');
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        livenessProbe:
          httpGet:
            path: /wp-admin/install.php
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /wp-admin/install.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsUser: 33
          runAsGroup: 33
          fsGroup: 33
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
      initContainers:
      - name: init-wordpress
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          # Set proper permissions for WordPress files
          chown -R 33:33 /var/www/html
          chmod -R 755 /var/www/html
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        securityContext:
          runAsUser: 0