name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: AWS region
        required: false
        default: us-west-2
      tf-state-bucket:
        description: S3 bucket for Terraform state (optional)
        required: false
      tf-lock-table:
        description: DynamoDB table for state locks (optional)
        required: false

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ github.event.inputs.aws-region || secrets.AWS_REGION || 'us-west-2' }}
      TF_STATE_BUCKET: ${{ github.event.inputs.tf-state-bucket || secrets.TF_STATE_BUCKET }}
      TF_STATE_LOCK_TABLE: ${{ github.event.inputs.tf-lock-table || secrets.TF_STATE_LOCK_TABLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init backend
        working-directory: terraform/environments/prod
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=wordpress-eks/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}"

      - name: Destroy
        working-directory: terraform/environments/prod
        run: |
          terraform destroy -auto-approve -var="aws_region=${AWS_REGION}"